name: MarriageMaster
author: GeorgH93
website: http://dev.bukkit.org/bukkit-plugins/marriage-master/
main: at.pcgamingfreaks.georgh.MarriageMaster.MarriageMaster
version: 1.3.3
softdepend: [Vault]
commands:
   marry:
      description: Main command
      usage: /marry
      
permissions:
  marry.*:
    description: Gives access to all MarriageMaster commands
    children:
      marry.list: true
      marry.pvpon: true  
      marry.pvpoff: true 
      marry.priest: true
      marry.tp: true
      marry.home: true
      marry.chat: true
      marry.setpriest: true
      marry.reload: true
      marry.listenchat: true
      marry.gift: true
  marry.admin:
    description: Gives acces to all Marriage Admin commands
    children:
      marry.reload: true
      marry.setpriest: true
      marry.priest: true
      marry.listenchat: true
  marry.list:
    description: Allows you to use the List command
    default: true
  marry.pvpon:
    description: Allows you to enable pvp with your partner
    default: true
  marry.pvpoff:
    description: Allows you to disable pvp with your partner
    default: true
  marry.priest:
    description: Allows you to marry two players
    default: op
  marry.tp:
    description: Allows you to tp to your partner
    default: true
  marry.home:
    description: Allows you to tp / set to your home
    default: true
  marry.chat:
    description: Allows you to chat with your partner
    default: true
  marry.gift:
    description: Allows you to gift items to your partner
    default: true
  marry.setpriest:
    description: Allows you to set a priest
    default: op
  marry.listenchat:
    description: Allows to see the private chat
    default: op
  marry.reload:
    description: Allows you to reload the config
    default: op