name: MarriageMaster
author: GeorgH93
website: http://dev.bukkit.org/bukkit-plugins/marriage-master/
main: at.pcgamingfreaks.georgh.MarriageMaster.MarriageMaster
version: 1.10.2
softdepend: [Vault]
commands:
   marry:
      description: Main command
      usage: /marry
      
permissions:
  marry.*:
    description: Gives access to all MarriageMaster commands
    children:
      marry.list: true
      marry.pvpon: true  
      marry.pvpoff: true 
      marry.priest: true
      marry.tp: true
      marry.home: true
      marry.chat.*: true
      marry.gift: true
      marry.kiss: true
      marry.setpriest: true
      marry.reload: true
      marry.listenchat: true
      marry.update: true
      marry.offlinedivorce: true
      marry.selfmarry: true
      marry.skiptpdelay: true
  marry.admin:
    description: Gives acces to all Marriage Admin commands
    children:
      marry.reload: true
      marry.setpriest: true
      marry.priest: true
      marry.listenchat: true
      marry.update: true
      marry.offlinedivorce: true
      marry.skiptpdelay: true
  marry.chat.*:
    description: Gives acces to all private message formats
    children:
      marry.chat: true
      marry.chat.color: true
      marry.chat.format: true
      marry.chat.magic: true
  marry.list:
    description: Allows you to use the List command
    default: true
  marry.pvpon:
    description: Allows you to enable pvp with your partner
    default: true
  marry.pvpoff:
    description: Allows you to disable pvp with your partner
    default: true
  marry.tp:
    description: Allows you to tp to your partner
    default: true
  marry.home:
    description: Allows you to tp / set to your home
    default: true
  marry.chat:
    description: Allows you to chat with your partner
    default: true
  marry.chat.color:
    description: Allows colors in private messages
    default: true
  marry.chat.format:
    description: Allows formating private messages (except magic)
    default: true
  marry.chat.magic:
    description: Allows magic format in private messages
    default: false
  marry.gift:
    description: Allows you to gift items to your partner
    default: true
  marry.kiss:
    description: Allows to kiss your partner
    default: true
  marry.selfmarry:
    description: Allows to marry an other player without a priest
    defualt: true
  marry.skiptpdelay:
    description: Allows to skip the delay on tps
    default: op
  marry.offlinedivorce:
    description: Allows a priest to divorce players when only one of them is online.
    default: op
  marry.priest:
    description: Allows you to marry two players
    default: op
  marry.setpriest:
    description: Allows you to set a priest
    default: op
  marry.listenchat:
    description: Allows to see the private chat
    default: op
  marry.update:
    description: Allows to update the plugin
    default: op
  marry.reload:
    description: Allows you to reload the config
    default: op